name: Propagate Bug

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  issues: write

jobs:

  checkLabels:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true && github.event.pull_request.labels.*.name[0]}}
    steps:
      - run: echo Check labels is not empty

  propagate:
    needs: [checkLabels]
    if: ${{github.event.pull_request.merged == true}}
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}

    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.PAT_TOKEN  }}


      - name: Create pull request to release if PR contains label and source was bug/*
        if: ${{ startsWith(github.head_ref, 'bug/') && startsWith(matrix.label, 'propagate:release/')}}
        env:
            GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          TARGET_BRANCH="${{matrix.label}}"
          TARGET_BRANCH="${TARGET_BRANCH#propagate:}"
          gh pr create \
            --title "Add bug correction to release" \
            --body "Add bug to release because of the presence of label propagate on the PR" \
            --head ${{github.head_ref}} \
            --base ${TARGET_BRANCH}